num_tab = int(input('Tabuada de qual número? '))

print('Eis aqui a tabudada do número {}:'.format(num_tab))

print('-' * 12)
print('{} x {:2} = {}'.format(num_tab, 1, num_tab * 1))
print('{} x {:2} = {}'.format(num_tab, 2, num_tab * 2))
print('{} x {:2} = {}'.format(num_tab, 3, num_tab * 3))
print('{} x {:2} = {}'.format(num_tab, 4, num_tab * 4))
print('{} x {:2} = {}'.format(num_tab, 5, num_tab * 5))
print('{} x {:2} = {}'.format(num_tab, 6, num_tab * 6))
print('{} x {:2} = {}'.format(num_tab, 7, num_tab * 7))
print('{} x {:2} = {}'.format(num_tab, 8, num_tab * 8))
print('{} x {:2} = {}'.format(num_tab, 9, num_tab * 9))
print('{} x {:2} = {}'.format(num_tab, 10, num_tab * 10))
print('-' * 12)